name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - protobuf=3.20.0
  - numpy=1.19.5
  - seaborn=0.12.1
  - pandas=1.2.5
  - pip
  - ipywidgets
  - pyarrow
  - pip:
      - wandb==0.10.31
      - ydata_profiling==4.0.0