name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - git=2.34.1
  - jupyterlab
  - numpy
  - seaborn
  - pandas
  - pip
  - pandas-profiling
  - pyarrow
  - pip:
      - wandb