name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core=1.0.6
  - matplotlib
  - pandas
  - numpy
  - git=2.34.1
  - pip
  - pip:
      - mlflow
      - wandb